<?php

namespace AppBundle\Repository;

/**
 * COmmentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class COmmentaireRepository extends \Doctrine\ORM\EntityRepository
{
}
