<?php

namespace AppBundle\Repository;

/**
 * dataUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dataUserRepository extends \Doctrine\ORM\EntityRepository
{
}
