<?php

namespace AppBundle\Repository;

/**
 * DataUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataUserRepository extends \Doctrine\ORM\EntityRepository
{
}
