app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_login:
    path:     /user/login
    defaults: { _controller: AppBundle:Security:login }

user_login_check:
    path:     /user/login/check
    defaults: { _controller: AppBundle:Security:check }

user_register:
    path:     /user/register
    defaults: { _controller: AppBundle:Registration:register }

user_dashboard:
    path:     /user/dashboard
    defaults: { _controller: AppBundle:Default:index }
