app:
    resource: "@AppBundle/Controller/"
    type:     annotation
home:
    path:     /
    defaults: { _controller: AppBundle:Default:index}

modify_user:
    path:    /reset
    defaults: { _controller: AppBundle:User:modifyUser }

user_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

user_profil:
    path:     /user/profil
    defaults: { _controller: AppBundle:User:showProfil }

user_login_check:
    path:     /user/login/check
    defaults: { _controller: AppBundle:Security:check }

user_register:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }

user_confirmed:
    path:     /user/confirmed
    defaults: { _controller: AppBundle:Registration:confirmed }

user_dashboard:
    path:     /user/dashboard
    defaults: { _controller: AppBundle:Default:index }

user_mailbox:
    path:     /user/dashboard/Mailbox
    defaults: { _controller: AppBundle:Mailbox:mails}

post:
    path:    /accueil   
    defaults: { _controller: AppBundle:Default:post }

post_new:
    path:    /post/new
    defaults: { _controller: AppBundle:Default:postNew }

messagerie:
    path:    /messagerie
    defaults: { _controller: AppBundle:Mailbox:messagerie }

messagerie_new:
    path:    /messagerie/new
    defaults: { _controller: AppBundle:Mailbox:messagerieNew }

#a partir d'ici ça ne sert plus à rien c'est que des test#
reset_password:
    path:     /reset/password
    defaults: { _controller: AppBundle:ChangePassword:changePassword}

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
